-- ====================================================================
-- AegisGuard AI — Supabase PostgreSQL Database Schema
-- Customer Support Intelligence & Phishing Threat Detection System
-- ====================================================================

-- Enable UUID extension if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Conversations Table
CREATE TABLE IF NOT EXISTS conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_id TEXT UNIQUE,
  customer_name TEXT,
  customer_email TEXT,
  channel TEXT CHECK (channel IN ('Email', 'Chat', 'Support Ticket', 'Contact Form', 'Social Media')),
  message TEXT NOT NULL,
  conversation_history TEXT,
  status TEXT DEFAULT 'Open',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Analyses Table
CREATE TABLE IF NOT EXISTS analyses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  category TEXT,
  issue TEXT,
  sentiment TEXT CHECK (sentiment IN ('Positive', 'Neutral', 'Negative')),
  emotion TEXT,
  urgency TEXT CHECK (urgency IN ('Low', 'Medium', 'High', 'Critical')),
  priority TEXT CHECK (priority IN ('Low', 'Medium', 'High', 'Critical')),
  customer_request TEXT,
  summary TEXT,
  resolution_status TEXT CHECK (resolution_status IN ('Resolved', 'Unresolved', 'Pending', 'Unknown')),
  recommended_action TEXT,
  confidence REAL DEFAULT 0.95,
  keywords TEXT,
  entities TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Threats Table
CREATE TABLE IF NOT EXISTS threats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  threat_detected INTEGER DEFAULT 0,
  threat_type TEXT,
  risk_level TEXT CHECK (risk_level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
  risk_score INTEGER DEFAULT 0,
  social_engineering INTEGER DEFAULT 0,
  social_engineering_techniques TEXT,
  credential_request INTEGER DEFAULT 0,
  otp_request INTEGER DEFAULT 0,
  suspicious_message INTEGER DEFAULT 0,
  reason TEXT,
  recommended_action TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Extracted URLs Table
CREATE TABLE IF NOT EXISTS urls (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  domain TEXT,
  subdomain TEXT,
  protocol TEXT,
  url_length INTEGER,
  uses_ip INTEGER DEFAULT 0,
  https INTEGER DEFAULT 1,
  suspicious_characters INTEGER DEFAULT 0,
  shortened INTEGER DEFAULT 0,
  lookalike INTEGER DEFAULT 0,
  risk_score INTEGER DEFAULT 0,
  risk_reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Extracted Emails Table
CREATE TABLE IF NOT EXISTS emails (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  domain TEXT,
  display_name TEXT,
  domain_mismatch INTEGER DEFAULT 0,
  lookalike INTEGER DEFAULT 0,
  free_mail INTEGER DEFAULT 0,
  risk_score INTEGER DEFAULT 0,
  risk_reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Performance Indexes
CREATE INDEX IF NOT EXISTS idx_conversations_channel ON conversations(channel);
CREATE INDEX IF NOT EXISTS idx_conversations_created ON conversations(created_at);
CREATE INDEX IF NOT EXISTS idx_analyses_category ON analyses(category);
CREATE INDEX IF NOT EXISTS idx_analyses_sentiment ON analyses(sentiment);
CREATE INDEX IF NOT EXISTS idx_analyses_priority ON analyses(priority);
CREATE INDEX IF NOT EXISTS idx_analyses_resolution ON analyses(resolution_status);
CREATE INDEX IF NOT EXISTS idx_threats_risk_level ON threats(risk_level);
CREATE INDEX IF NOT EXISTS idx_threats_threat_detected ON threats(threat_detected);
CREATE INDEX IF NOT EXISTS idx_urls_risk_score ON urls(risk_score);
CREATE INDEX IF NOT EXISTS idx_urls_domain ON urls(domain);

-- Enable Row Level Security (RLS) & Public Read/Write Policies for API Service
ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE analyses ENABLE ROW LEVEL SECURITY;
ALTER TABLE threats ENABLE ROW LEVEL SECURITY;
ALTER TABLE urls ENABLE ROW LEVEL SECURITY;
ALTER TABLE emails ENABLE ROW LEVEL SECURITY;

-- Allow anon and service_role access for REST API
CREATE POLICY "Allow all operations for service and anon on conversations" ON conversations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations for service and anon on analyses" ON analyses FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations for service and anon on threats" ON threats FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations for service and anon on urls" ON urls FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all operations for service and anon on emails" ON emails FOR ALL USING (true) WITH CHECK (true);
